-- Chat Assistant LB-19 fix round (Kiara's test report, 8 Oct 2026). Additive only;
-- safe to run whether or not 0009 already ran (it may have, through a preview build).
--  * closed_at: when the bot's closing message went out (name + number collected).
--    The chat now stays OPEN for 10 more quiet minutes so anything the visitor types
--    after the closing message lands in the SAME chat and the SAME single email.
--    The chat then ends (end_reason 'closing'), or earlier on /api/chat/end.
--  * seq: insertion order, a deterministic tie-break when two chats of one session
--    share the same started_at (latestChat / ordering never depends on uuid order).
alter table chat_conversations add column if not exists closed_at timestamptz;
alter table chat_conversations add column if not exists seq bigint generated by default as identity;
create index if not exists chat_conversations_session_seq_idx on chat_conversations (session_id, started_at desc, seq desc);
