/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsMasterRouteImport } from './routes/accounts-master'
import { Route as AvailableRouteImport } from './routes/available'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DenRouteImport } from './routes/den'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ShipRouteImport } from './routes/ship'
import { Route as StockRouteImport } from './routes/stock'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksPurchasesRouteImport } from './routes/books/purchases'
import { Route as BooksSalesRouteImport } from './routes/books/sales'
import { Route as BooksStockRouteImport } from './routes/books/stock'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsMasterRoute = AccountsMasterRouteImport.update({
  id: '/accounts-master',
  path: '/accounts-master',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailableRoute = AvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DenRoute = DenRouteImport.update({
  id: '/den',
  path: '/den',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipRoute = ShipRouteImport.update({
  id: '/ship',
  path: '/ship',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksPurchasesRoute = BooksPurchasesRouteImport.update({
  id: '/books/purchases',
  path: '/books/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSalesRoute = BooksSalesRouteImport.update({
  id: '/books/sales',
  path: '/books/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksStockRoute = BooksStockRouteImport.update({
  id: '/books/stock',
  path: '/books/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts-master': typeof AccountsMasterRoute
  '/available': typeof AvailableRoute
  '/contact': typeof ContactRoute
  '/den': typeof DenRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/ship': typeof ShipRoute
  '/stock': typeof StockRoute
  '/books/purchases': typeof BooksPurchasesRoute
  '/books/sales': typeof BooksSalesRoute
  '/books/stock': typeof BooksStockRoute
  '/books/': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts-master': typeof AccountsMasterRoute
  '/available': typeof AvailableRoute
  '/contact': typeof ContactRoute
  '/den': typeof DenRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/ship': typeof ShipRoute
  '/stock': typeof StockRoute
  '/books/purchases': typeof BooksPurchasesRoute
  '/books/sales': typeof BooksSalesRoute
  '/books/stock': typeof BooksStockRoute
  '/books': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts-master': typeof AccountsMasterRoute
  '/available': typeof AvailableRoute
  '/contact': typeof ContactRoute
  '/den': typeof DenRoute
  '/login': typeof LoginRoute
  '/purchases': typeof PurchasesRoute
  '/sales': typeof SalesRoute
  '/ship': typeof ShipRoute
  '/stock': typeof StockRoute
  '/books/purchases': typeof BooksPurchasesRoute
  '/books/sales': typeof BooksSalesRoute
  '/books/stock': typeof BooksStockRoute
  '/books/': typeof BooksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts-master'
    | '/available'
    | '/contact'
    | '/den'
    | '/login'
    | '/purchases'
    | '/sales'
    | '/ship'
    | '/stock'
    | '/books/purchases'
    | '/books/sales'
    | '/books/stock'
    | '/books/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts-master'
    | '/available'
    | '/contact'
    | '/den'
    | '/login'
    | '/purchases'
    | '/sales'
    | '/ship'
    | '/stock'
    | '/books/purchases'
    | '/books/sales'
    | '/books/stock'
    | '/books'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accounts-master'
    | '/available'
    | '/contact'
    | '/den'
    | '/login'
    | '/purchases'
    | '/sales'
    | '/ship'
    | '/stock'
    | '/books/purchases'
    | '/books/sales'
    | '/books/stock'
    | '/books/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsMasterRoute: typeof AccountsMasterRoute
  AvailableRoute: typeof AvailableRoute
  ContactRoute: typeof ContactRoute
  DenRoute: typeof DenRoute
  LoginRoute: typeof LoginRoute
  PurchasesRoute: typeof PurchasesRoute
  SalesRoute: typeof SalesRoute
  ShipRoute: typeof ShipRoute
  StockRoute: typeof StockRoute
  BooksPurchasesRoute: typeof BooksPurchasesRoute
  BooksSalesRoute: typeof BooksSalesRoute
  BooksStockRoute: typeof BooksStockRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-master': {
      id: '/accounts-master'
      path: '/accounts-master'
      fullPath: '/accounts-master'
      preLoaderRoute: typeof AccountsMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/available': {
      id: '/available'
      path: '/available'
      fullPath: '/available'
      preLoaderRoute: typeof AvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/den': {
      id: '/den'
      path: '/den'
      fullPath: '/den'
      preLoaderRoute: typeof DenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ship': {
      id: '/ship'
      path: '/ship'
      fullPath: '/ship'
      preLoaderRoute: typeof ShipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/purchases': {
      id: '/books/purchases'
      path: '/books/purchases'
      fullPath: '/books/purchases'
      preLoaderRoute: typeof BooksPurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/sales': {
      id: '/books/sales'
      path: '/books/sales'
      fullPath: '/books/sales'
      preLoaderRoute: typeof BooksSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/stock': {
      id: '/books/stock'
      path: '/books/stock'
      fullPath: '/books/stock'
      preLoaderRoute: typeof BooksStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsMasterRoute: AccountsMasterRoute,
  AvailableRoute: AvailableRoute,
  ContactRoute: ContactRoute,
  DenRoute: DenRoute,
  LoginRoute: LoginRoute,
  PurchasesRoute: PurchasesRoute,
  SalesRoute: SalesRoute,
  ShipRoute: ShipRoute,
  StockRoute: StockRoute,
  BooksPurchasesRoute: BooksPurchasesRoute,
  BooksSalesRoute: BooksSalesRoute,
  BooksStockRoute: BooksStockRoute,
  BooksIndexRoute: BooksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
